### ISSUE TITLE
Change keycloak configurations

### ISSUE THREAD

**Issue by HLLissau** [gh05tdog/DAPM_Master_Thesis_Group_D#187]
On the loginpage, we currently show 
![image](https://github.com/user-attachments/assets/32b5f8fc-a9fd-4ab9-9d59-4a386aa1eee2)

The realm display name  in keycloak should be changed to a proper name "DAPM-E by group D" or similar.

Expected:
![image](https://github.com/user-attachments/assets/d0242e98-cf55-4a49-97c3-7dee8dc05125)

**Comment by gh05tdog** [comment]
This can not be changed by our current setup. It would either require us to rethink how we initilice our keycloak. Or we chnaged the realm name. Either way i think this is not worth our time

The problem lies in that this can not be changed in the realm.json file. It has to be changed from the interface.
